### ISSUE TITLE
How to implement Speech-To-Text?

### ISSUE THREAD

**Issue by btmelody** [btmelody/pdf-chatbot#3]
I tried several times to implement speech-to-text but the result was not successful.
I almost approved but got this error
![image](https://github.com/btmelody/pdf-chatbot/assets/125443259/0c53a014-cb78-4832-8c36-92d476f62724)
Hey Chandler, please give me the tips for that.
Thanks

**Comment by leighhayes** [comment]
Hi @btmelody 
I just correct that feature. Now it is working well.
I don't know why the error occurred in react-speech-recognition.
Anyway, now is working well so please check the deployment production
